## -*- mode: perl; -*-
## Build configuration targets for openssl-team members

my %targets = (
    "VC-WIN64A-DBG" => {
        inherit_from     => [ 'VC-WIN64A' ],
        shlib_variant    => "d",
    },
    "VC-WIN64A-REL" => {
        inherit_from     => [ 'VC-WIN64A' ],
    },
);
